services:
  backend:
    image: django-api-demo:1.0.0
    container_name: django-backend
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    depends_on:
      - backend
    image: docker-demo-front:1.0.0
    container_name: django-frontend
    env_file:
      - .front.env
    ports:
      - "5000:80"
